Fix missing include in externs.h
cisco/ChezScheme pull request #552
Opened 2021-03-03 19:01 UTC by ismaell

The time.h header is required to make the timespec struct available for
the prototypes.

Fixes: https://github.com/cisco/ChezScheme/issues/281

2021-03-08 14:58 UTC, burgerrg requested changes
Thank you for this fix! Now that externs.h includes time.h, please remove the include of time.h from the C files that already include externs.h. Then update LOG.

2021-03-09 16:40 UTC, ismaell commented
@burgerrg just to clarify the update: I've addressed both things (it required to make the inclusion unconditional) and squashed everything into a single commit.

2021-03-09 17:16 UTC, burgerrg commented
Thank you! Do we need the `#include <sys/time.h>` lines in scheme.c and stats.c?

2021-03-09 19:15 UTC, burgerrg approved these changes

2021-03-09 19:16 UTC, merged

2021-03-09 19:16 UTC, burgerrg commented
Thanks again for this fix!

2021-03-10 09:54 UTC, ismaell commented
> On macOS, the sys/time.h header is needed for stats.c.

Neither header requires the other's definitions, so I think that's universal.